import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api, RouterOutputs } from "~/utils/api";
import { SignInButton, SignOutButton, SignIn, useUser } from "@clerk/nextjs";

const CreatePostWizard = () => { 
  const {user} = useUser();

  if (!user) return null;

  return <div className="flex gap-3 w-full">
    <img 
      src={user.profileImageUrl} 
      alt="Profile Image"
      className="w-14 h-14 rounded-full" 
    />
    <input placeholder="Type some emojis!" className="bg-transparent grow outline-none"/>
  </div>
}

//type PostWithUser = RouterOutputs["posts"]["getAll"][number]; //[number] means we want an element of the array

// const PostView = (props: {post: PostWithUser }) => {
//   return (
//     <div key={post.id} className="p-8 border-b border-slate-400">{post.content}</div>
//   )
// }

const Home: NextPage = () => {
  const user = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) return <div>Loading...</div>;

  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
      <div className="border-x border-slate-400 h-full w-full md:max-w-2xl">
        <div className="flex border-b border-slate-400 p-4">
          {!user.isSignedIn && <div className="flex justify-center"><SignInButton /></div>}
          {user.isSignedIn && <CreatePostWizard />}
        </div>
        <div className="flex flex-col">
          {data?.map(({post, author}) => (
            <div key={post.id} className="p-8 border-b border-slate-400">{post.content}</div>
          ))}
        </div>
      </div>
      </main>
    </>
  );
};

export default Home;
