import { type NextPage } from "next";
import Head from "next/head";

//[id].tsx - when we use Nextjs router, will have access to the id

const SinglePostPage: NextPage = () => {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex justify-center h-screen">
      <div>
       Single Post Page
      </div>
      </main>
    </>
  );
};

export default SinglePostPage;
